name: test-application

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action
      - run: npm i
      - run: npm run dev
      - run: npm run test
