name: test-application

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
      - run: yarn

      - name: Run application
      - run: yarn dev

      - name: Run unit tests
      - run: yarn test
