name: test-application

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Run project
        run: yarn start &

      - name: Run unit tests
        run: yarn test:unit

      - name: Run e2e tests
        run: yarn test:e2e
